import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef, confusion_matrix, classification_report
import os

# Set page config
st.set_page_config(page_title="Breast Cancer Classification", layout="wide")

st.title("Breast Cancer Classification App")
st.markdown("""
This application demonstrates multiple Machine Learning models for classifying breast cancer tumors as Malignant or Benign.
""")

# Sidebar for Model Selection
st.sidebar.header("Model Selection")
model_options = [
    "Logistic Regression",
    "Decision Tree",
    "KNN",
    "Naive Bayes",
    "Random Forest",
    "XGBoost"
]
selected_model_name = st.sidebar.selectbox("Choose a Classification Model", model_options)

# Load Model
@st.cache_resource
def load_model(model_name):
    filename = f"model/{model_name.replace(' ', '_').lower()}.pkl"
    try:
        model = joblib.load(filename)
        return model
    except FileNotFoundError:
        st.error(f"Model file not found: {filename}.\nPlease train the models first using 'python model/train_models.py'.")
        return None

# Load Scaler
@st.cache_resource
def load_scaler():
    try:
        return joblib.load('model/scaler.pkl')
    except FileNotFoundError:
        st.error("Scaler not found. Please ensure 'model/scaler.pkl' exists.")
        return None

model = load_model(selected_model_name)
scaler = load_scaler()

# Main Content
st.header("Upload Test Data")
uploaded_file = st.file_uploader("Upload your input CSV file (must contain features and 'target' column)", type=["csv"])

if uploaded_file is not None:
    try:
        data = pd.read_csv(uploaded_file)
        st.write("Uploaded Data Sample:")
        st.dataframe(data)
        
        # Check if target column exists for evaluation
        target_col = 'target' # Assuming the uploaded file has 'target' as per assignment flow imply evaluation
        
        if target_col in data.columns:
            X_test = data.drop(columns=[target_col])
            y_test = data[target_col]
            
            # Scale data
            if scaler:
                # Ensure columns match
                # Ideally we would check feature names here
                try:
                    X_test_scaled = scaler.transform(X_test)
                except ValueError as e:
                    st.error(f"Feature mismatch: {e}")
                    st.stop()
            else:
                st.stop()
            
            if model:
                # Predictions
                y_pred = model.predict(X_test_scaled)
                y_prob = model.predict_proba(X_test_scaled)[:, 1] if hasattr(model, "predict_proba") else y_pred
                
                # Metrics
                st.subheader("Evaluation Metrics")
                col1, col2, col3 = st.columns(3)
                col1.metric("Accuracy", f"{accuracy_score(y_test, y_pred):.4f}")
                col2.metric("AUC Score", f"{roc_auc_score(y_test, y_prob):.4f}")
                col3.metric("F1 Score", f"{f1_score(y_test, y_pred):.4f}")
                
                col4, col5, col6 = st.columns(3)
                col4.metric("Precision", f"{precision_score(y_test, y_pred):.4f}")
                col5.metric("Recall", f"{recall_score(y_test, y_pred):.4f}")
                col6.metric("MCC", f"{matthews_corrcoef(y_test, y_pred):.4f}")
                
                # Confusion Matrix
                st.subheader("Confusion Matrix")
                cm = confusion_matrix(y_test, y_pred)
                fig, ax = plt.subplots()
                sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax)
                ax.set_xlabel('Predicted')
                ax.set_ylabel('Actual')
                st.pyplot(fig)
                
                # Classification Report
                st.subheader("Classification Report")
                report = classification_report(y_test, y_pred, output_dict=True)
                st.dataframe(pd.DataFrame(report).transpose())
                
        else:
            st.warning("Uploaded CSV does not contain 'target' column. Evaluation metrics cannot be calculated.")
            
    except Exception as e:
        st.error(f"Error processing file: {e}")
else:
    st.info("Please upload a CSV file to proceed. You can use 'data/test_data.csv' generated by the training script.")
